# Generated by Django 3.1 on 2020-09-07 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moviename', models.CharField(max_length=50)),
                ('heroname', models.CharField(max_length=50)),
                ('heroineame', models.CharField(max_length=50)),
                ('poster', models.ImageField(null='True', upload_to='poster/')),
                ('directorname', models.CharField(max_length=50)),
            ],
        ),
    ]
